# Generated by Django 4.2.6 on 2023-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_members',
            field=models.IntegerField(default=0),
        ),
    ]
