# Generated by Django 3.0.3 on 2023-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Waiting'), (2, 'Started')], default=0),
        ),
    ]
