# Generated by Django 4.2.7 on 2023-11-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avgExp',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
