# Generated by Django 4.2.7 on 2023-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room_avgexp_alter_moment_id_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currentMoment',
            field=models.IntegerField(default=1),
        ),
    ]
